--Join the film to the film_actor table.
SELECT F.FILM_ID, F.TITLE, F.DESCRIPTION, F.RELEASE_YEAR, F.LANGUAGE_ID, F.RENTAL_DURATION, F.RENTAL_RATE, F.LENGTH, F.REPLACEMENT_COST, F.RATING, F.LAST_UPDATE, F.SPECIAL_FEATURES, F.FULLTEXT, FILM_ACTOR.ACTOR_ID, FILM_ACTOR.FILM_ID, FILM_ACTOR.LAST_UPDATE
FROM FILM F
INNER JOIN FILM_ACTOR ON F.FILM_ID=FILM_ACTOR.FILM_ID;

--Join the actor table to the film_actor table. 
SELECT A.ACTOR_ID, A.FIRST_NAME, A.LAST_NAME, A.LAST_UPDATE, FILM_ACTOR.ACTOR_ID, FILM_ACTOR.FILM_ID, FILM_ACTOR.FILM_ID
FROM ACTOR A
INNER JOIN FILM_ACTOR ON A.ACTOR_ID=FILM_ACTOR.ACTOR_ID;

--Try to join the actor, film_actor, and film table together (3 joins!)
SELECT
  ACTOR.ACTOR_ID,
  ACTOR.FIRST_NAME,
  ACTOR.LAST_NAME,
  FILM_ACTOR.ACTOR_ID,
  FILM.FILM_ID
FROM ACTOR
JOIN FILM_ACTOR
  ON ACTOR.ACTOR_ID = FILM_ACTOR.FILM_ID
JOIN FILM
  ON FILM.FILM_ID = FILM_ACTOR.FILM_ID;

